### ISSUE TITLE
401 Client Error: Unauthorized

### ISSUE THREAD

**Issue by matko031** [mi01/vaccine-booker-berlin#2]
I get a problem on line 442 with `patients = docto.get_patients()`, it throws `woob.browser.exceptions.ClientError: 401 Client Error: Unauthorized`. I double checked and my credentials are correct. Any idea what might cause this issue?

**Comment by mi01** [comment]
Thanks for the feedback. Catching this exception seems meaningful, i will fix this. In general the Doctolib servers are sometimes a bit delicate, also during the login they reply with 503 quite often. When you retry, does this error occur always, or just sometimes?

**Comment by throwaway263** [comment]
this error does not go away until an auth step has been completed. doctolib probably thinks this is a new "browser" or "device", perhaps based on the UserAgent.

this doctoshotgun fork has a workaround: https://github.com/lionawurscht/doctoshotgun (relevant change [here]( https://github.com/lionawurscht/doctoshotgun/commit/23729ce081ab2881a932fff062263545827772de#diff-f03662f918c6bb85b9a50397ab93b136afa66a7a9b1eb8d6dfb2ac305fb0fba3R169-R230 ))

quick fix for end users to get `vaccine-booker-berlin` working:
- download the above fork
- add `selenium` to requirements.txt and install requirements
- replace `doctolib.fr` with `doctolib.de` in the python script
- run it once
- complete auth steps, e.g. click link in confirmation mail
- now all similar scripts, such as `vaccine-booker-berlin` work

i'm not a python guy, otherwise i'd love to prepare a PR to add this functionality. thanks for building this @mi01 :heart:

**Comment by mi01** [comment]
Thanks for the clarification, Doctolib never requested 2-factor authentication for me, except when registering my account. I need to figure out how to provoke this, just changing the UserAgent and IP does not work, so i can test the solution above, before adopting it.

**Comment by throwaway263** [comment]
2FA must be somehow triggered by the script on its first run, because logging into the site through my browser didn't trigger 2FA for me. i'm also pretty certain that it's not just the IP address, because I used the same for signing up on the doctolib site and running the script.

**Comment by mi01** [comment]
Since Doctolib enabled 2FA for everyone now, i fixed this in 6c23f3426c7733bedec78104b985a94c8f7a9159.
